---
image: debian:11
cache:
  key: apt
  paths:
    - apt-cache/
cache:
  key: custom
  paths:
    - semicache/
pages:
  stage: deploy
  script:
    - export APT_CACHE_DIR=`pwd`/apt-cache
    - mkdir -pv $APT_CACHE_DIR
    - apt-get update && apt-get install -y openjdk-11-jdk maven clang clang-format wabt emscripten
    - mvn exec:java
  artifacts:
    paths:
      - public
  only:
    - master