on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: debian:11
    steps:
      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/semicache
          key: cache
          restore-keys: cache
      - uses: actions/checkout@v2
      - name: Render
        run: |
          export APT_CACHE_DIR=`pwd`/semicache/apt-cache
          mkdir -pv $APT_CACHE_DIR
          export SC_MAVEN_DIR=`pwd`/semicache/maven
          mkdir -pv $SC_MAVEN_DIR
          apt-get update && apt-get install -y openjdk-11-jdk maven clang clang-format wabt emscripten
          mvn --batch-mode -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -Dmaven.repo.local=$SC_MAVEN_DIR compile exec:java
      - name: Prep for deploy
        # Workaround for the github actions container mess and included actions breaking in containers
        run: apt-get install git
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ~/public
